"""
Django settings for portfolio_site project.

Generated by 'django-admin startproject' using Django 6.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
import sys
from pathlib import Path

import dj_database_url
from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv

try:
    import whitenoise  # noqa: F401
    HAS_WHITENOISE = True
except ImportError:
    HAS_WHITENOISE = False

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env file (ignored in production if not present)
load_dotenv(BASE_DIR / '.env')


def _env_bool(name, default=False):
    raw = os.environ.get(name)
    if raw is None:
        return default
    return raw.strip().lower() in {"1", "true", "yes", "on"}


def _env_list(name, default=""):
    raw = os.environ.get(name, default)
    return [item.strip() for item in raw.split(",") if item.strip()]


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

IS_RENDER = bool(os.environ.get("RENDER"))
IS_VERCEL = bool(os.environ.get("VERCEL"))
IS_PAAS = IS_RENDER or IS_VERCEL

DEBUG = _env_bool("DEBUG", default=not IS_PAAS)

SECRET_KEY = os.environ.get("SECRET_KEY") or os.environ.get("DJANGO_SECRET_KEY", "")
if not SECRET_KEY:
    if DEBUG or "collectstatic" in sys.argv:
        SECRET_KEY = "django-insecure-dev-only-change-me"
    else:
        raise ImproperlyConfigured("SECRET_KEY must be set when DEBUG is False.")

ALLOWED_HOSTS = _env_list("ALLOWED_HOSTS", "127.0.0.1,localhost,testserver")
if IS_RENDER:
    ALLOWED_HOSTS.extend([".onrender.com"])
    render_host = os.environ.get("RENDER_EXTERNAL_HOSTNAME")
    if render_host:
        ALLOWED_HOSTS.append(render_host)
if IS_VERCEL:
    ALLOWED_HOSTS.extend([".vercel.app", ".now.sh"])
    vercel_url = os.environ.get("VERCEL_URL")
    if vercel_url:
        ALLOWED_HOSTS.append(vercel_url)
    prod_url = os.environ.get("VERCEL_PROJECT_PRODUCTION_URL")
    if prod_url:
        ALLOWED_HOSTS.append(prod_url.split("://")[-1])

CSRF_TRUSTED_ORIGINS = _env_list(
    "CSRF_TRUSTED_ORIGINS",
    "http://127.0.0.1:8000,http://localhost:8000" if DEBUG else "",
)
if IS_RENDER:
    CSRF_TRUSTED_ORIGINS.append("https://*.onrender.com")
    render_url = os.environ.get("RENDER_EXTERNAL_URL")
    if render_url:
        CSRF_TRUSTED_ORIGINS.append(render_url.rstrip("/"))
if IS_VERCEL:
    CSRF_TRUSTED_ORIGINS.extend([
        "https://*.vercel.app",
        "https://*.now.sh",
    ])
    vercel_url = os.environ.get("VERCEL_URL")
    if vercel_url:
        CSRF_TRUSTED_ORIGINS.append(f"https://{vercel_url}")
    prod_url = os.environ.get("VERCEL_PROJECT_PRODUCTION_URL")
    if prod_url:
        origin = prod_url if prod_url.startswith("http") else f"https://{prod_url}"
        CSRF_TRUSTED_ORIGINS.append(origin)


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'storages',
    'portfolio.apps.PortfolioConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
]
if HAS_WHITENOISE:
    MIDDLEWARE.append('whitenoise.middleware.WhiteNoiseMiddleware')
MIDDLEWARE += [
    'portfolio_site.middleware.SecurityHeadersMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'portfolio_site.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'portfolio_site.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases
#
# When DATABASE_URL is set (e.g. in .env or in the hosting environment),
# Django connects to that PostgreSQL database.
# When DATABASE_URL is not set, it falls back to the local SQLite file so
# the project still runs without any environment setup.

_DATABASE_URL = os.environ.get('DATABASE_URL')
_COLLECTING_STATIC = "collectstatic" in sys.argv

if IS_PAAS and not _DATABASE_URL and not _COLLECTING_STATIC:
    raise ImproperlyConfigured(
        "DATABASE_URL is required on Render (use the existing Supabase PostgreSQL URL)."
    )

if _DATABASE_URL:
    DATABASES = {
        'default': dj_database_url.parse(
            _DATABASE_URL,
            conn_max_age=0 if IS_VERCEL else 600,
            conn_health_checks=not IS_VERCEL,
            ssl_require=_env_bool("DB_SSL_REQUIRE", default=True),
        )
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_URL = '/media/'
MEDIA_ROOT = Path("/tmp/media") if IS_VERCEL else (BASE_DIR / 'media')

WHITENOISE_MAX_AGE = 31536000
WHITENOISE_USE_FINDERS = DEBUG

# ── Supabase Storage (S3-compatible) ─────────────────────────────────────────
# Set these vars in .env / Render dashboard to enable cloud media.
# Without them, local FileSystemStorage is used (fine for dev, breaks on Render).

_sb_url    = os.environ.get("SUPABASE_URL", "")
_sb_key    = os.environ.get("SUPABASE_SERVICE_KEY", "")
_sb_bucket = os.environ.get("SUPABASE_BUCKET", "media")
_sb_region = os.environ.get("SUPABASE_REGION", "ap-southeast-2")
# Dedicated S3 credentials — generated from Supabase Dashboard → Storage → S3 Access Keys
_sb_s3_access_key = os.environ.get("SUPABASE_S3_ACCESS_KEY", "")
_sb_s3_secret_key = os.environ.get("SUPABASE_S3_SECRET_KEY", "")
_sb_s3_endpoint   = os.environ.get("SUPABASE_S3_ENDPOINT", "").strip()

_USE_SUPABASE_STORAGE = bool(_sb_url and _sb_s3_access_key and _sb_s3_secret_key and _sb_bucket)

if _USE_SUPABASE_STORAGE:
    MEDIA_URL = f"{_sb_url}/storage/v1/object/public/{_sb_bucket}/"

if _USE_SUPABASE_STORAGE:
    # Supabase vars present — use S3 backend always, even in local dev
    STORAGES = {
        "default": {
            "BACKEND": "storages.backends.s3.S3Storage",
            "OPTIONS": {
                "access_key":      _sb_s3_access_key,
                "secret_key":      _sb_s3_secret_key,
                "bucket_name":     _sb_bucket,
                "endpoint_url":    _sb_s3_endpoint,
                "region_name":     _sb_region,
                "addressing_style": "path",
                "querystring_auth": False,
                "file_overwrite":  False,
            },
        },
        "staticfiles": {
            "BACKEND": (
                "whitenoise.storage.CompressedStaticFilesStorage"
                if HAS_WHITENOISE
                else "django.contrib.staticfiles.storage.StaticFilesStorage"
            ),
        },
    }
elif not DEBUG:
    # Production without Supabase — warn loudly in Render logs
    import logging as _logging
    _logging.getLogger("portfolio.settings").warning(
        "SUPABASE_S3_ACCESS_KEY/SUPABASE_S3_SECRET_KEY not set — "
        "media uploads use ephemeral disk and will be lost on redeploy."
    )
    STORAGES = {
        "default": {"BACKEND": "django.core.files.storage.FileSystemStorage"},
        "staticfiles": {
            "BACKEND": (
                "whitenoise.storage.CompressedStaticFilesStorage"
                if HAS_WHITENOISE
                else "django.contrib.staticfiles.storage.StaticFilesStorage"
            ),
        },
    }

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Uploads and request size limits
DATA_UPLOAD_MAX_MEMORY_SIZE = 5 * 1024 * 1024
FILE_UPLOAD_MAX_MEMORY_SIZE = 5 * 1024 * 1024
DATA_UPLOAD_MAX_NUMBER_FIELDS = 200

# Cookies / browser security
SESSION_COOKIE_HTTPONLY = True
CSRF_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = "Lax"
CSRF_COOKIE_SAMESITE = "Lax"
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = "DENY"
SECURE_REFERRER_POLICY = "strict-origin-when-cross-origin"
SECURE_CROSS_ORIGIN_OPENER_POLICY = "same-origin"

if not DEBUG:
    SECURE_SSL_REDIRECT = _env_bool("SECURE_SSL_REDIRECT", default=IS_PAAS)
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = int(os.environ.get("SECURE_HSTS_SECONDS", "31536000"))
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")


# ── Email (Gmail SMTP) ────────────────────────────────────────────────────────
# Set EMAIL_HOST_USER and EMAIL_HOST_PASSWORD in .env / Render dashboard.
# Without them Django prints to the console (safe for dev).

_email_user = os.environ.get("EMAIL_HOST_USER", "")
_email_pass = os.environ.get("EMAIL_HOST_PASSWORD", "")

if _email_user and _email_pass:
    EMAIL_BACKEND    = "django.core.mail.backends.smtp.EmailBackend"
    EMAIL_HOST       = "smtp.gmail.com"
    EMAIL_PORT       = 587
    EMAIL_USE_TLS    = True
    EMAIL_HOST_USER  = _email_user
    EMAIL_HOST_PASSWORD = _email_pass
    DEFAULT_FROM_EMAIL  = f"Portfolio Contact <{_email_user}>"
    SERVER_EMAIL        = _email_user
else:
    EMAIL_BACKEND   = "django.core.mail.backends.console.EmailBackend"
    EMAIL_HOST_USER = _email_user

# Address that receives contact-form notification emails
CONTACT_NOTIFY_EMAIL = os.environ.get("CONTACT_NOTIFY_EMAIL", _email_user)

CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        "LOCATION": "portfolio",
        "TIMEOUT": 120,
        "OPTIONS": {"MAX_ENTRIES": 256},
    }
}

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {"class": "logging.StreamHandler"},
    },
    "root": {"handlers": ["console"], "level": "INFO"},
}
