# Generated by Django 6.1.1 on 2026-09-19 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.CharField(max_length=150)),
                ('role', models.CharField(blank=True, help_text='Leave blank to fall back to the experience type label', max_length=150)),
                ('exp_type', models.CharField(choices=[('internship', 'Internship / Industrial Training'), ('training', 'Training'), ('work', 'Work Experience')], default='internship', max_length=20)),
                ('location', models.CharField(blank=True, max_length=120)),
                ('start_date', models.CharField(help_text='e.g. 15 May 2023', max_length=30)),
                ('end_date', models.CharField(blank=True, help_text='Leave blank for a single-day entry or if ongoing', max_length=30)),
                ('description', models.TextField(blank=True, help_text='What you did / learned — easy to fill in or edit later')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Experience',
                'ordering': ['order', '-start_date'],
            },
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['category', 'order', 'name']},
        ),
        migrations.AddField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('programming', 'Programming'), ('web', 'Web'), ('backend', 'Backend'), ('database', 'Database'), ('app', 'Application Development'), ('other', 'Other')], default='programming', max_length=20),
        ),
        migrations.AlterField(
            model_name='education',
            name='degree',
            field=models.CharField(help_text='e.g. Diploma in Computer Engineering', max_length=150),
        ),
        migrations.AlterField(
            model_name='education',
            name='start_year',
            field=models.CharField(blank=True, help_text='Leave blank if you only want to show a completion year', max_length=10),
        ),
    ]
