# Generated by Django 6.1.1 on 2026-09-19 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_experience_alter_skill_options_skill_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='learning_focus',
            field=models.CharField(blank=True, help_text='Comma-separated interests / learning directions, e.g. Data Analytics, Web Development', max_length=200),
        ),
    ]
