# Generated by Django 5.2.17 on 2026-09-21 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_audit_content_defaults'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, help_text='Your photo for the hero section. A square image (about 600×600) works best.', null=True, upload_to='profile/'),
        ),
    ]
