# Generated by Django 5.2.17 on 2026-09-23 17:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_alter_profile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, help_text='Your photo for the hero section. A square image (about 600×600) works best. JPG, PNG or WebP only.', null=True, upload_to='profile/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='resume_file',
            field=models.FileField(blank=True, help_text='Upload a PDF resume for the Resume button', null=True, upload_to='resume/', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
    ]
