# Generated by Django 5.2.17 on 2026-09-23 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0006_tighten_profile_file_validators"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="open_to",
            field=models.CharField(
                blank=True,
                default="Internships & junior roles",
                help_text="Main line in the About sidebar “Open to” card",
                max_length=120,
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="open_to_note",
            field=models.CharField(
                blank=True,
                default="Web, applications, and data analytics work",
                help_text="Supporting line under “Open to”",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="learning_focus",
            field=models.CharField(
                blank=True,
                help_text="Currently exploring chips. Comma-separated, e.g. Data Analytics, Web Development",
                max_length=200,
            ),
        ),
    ]
