# Generated by Django 5.2.17 on 2026-10-02 06:25

import django.core.validators
import portfolio.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_alter_project_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='about_approach',
            field=models.CharField(blank=True, default='Building practical, working tools rather than tutorials', help_text='About section: Approach', max_length=250),
        ),
        migrations.AddField(
            model_name='profile',
            name='about_currently',
            field=models.CharField(blank=True, default='Strengthening SQL, Python and Power BI for analytics roles', help_text='About section: Currently', max_length=250),
        ),
        migrations.AddField(
            model_name='profile',
            name='about_focus',
            field=models.CharField(blank=True, default='Web & application development, with a growing base in data analytics', help_text='About section: Focus', max_length=250),
        ),
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.CharField(blank=True, default='WEB DEVELOPMENT', help_text='e.g. WEB DEVELOPMENT, DATA ANALYTICS, APPLICATION DEVELOPMENT', max_length=100),
        ),
        migrations.AddField(
            model_name='project',
            name='date_range',
            field=models.CharField(blank=True, help_text='e.g. Oct 2024 – Jan 2025', max_length=60),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, help_text='Your photo for the hero section. A square image (about 600×600) works best. JPG, PNG or WebP only.', null=True, upload_to=portfolio.models.upload_profile_image, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='resume_file',
            field=models.FileField(blank=True, help_text='Upload a PDF resume for the Resume button', null=True, upload_to=portfolio.models.upload_resume, validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=portfolio.models.upload_project_image, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])]),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_url',
            field=models.URLField(blank=True, help_text='Live site / demo link (leave blank if no live demo)', verbose_name='Live Demo URL'),
        ),
        migrations.AlterField(
            model_name='project',
            name='source_url',
            field=models.URLField(blank=True, help_text='Code repository link', verbose_name='GitHub / View Code URL'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('programming', 'Programming'), ('web', 'Web'), ('backend', 'Backend'), ('database', 'Database'), ('app', 'Application Development'), ('learning', 'Currently Learning'), ('other', 'Other')], default='programming', max_length=20),
        ),
    ]
